-- Run sql/baptism_records.sql first; it defines current_staff_parish_id().

create table if not exists public.confirmation_records (
  id bigint generated by default as identity not null,
  year_confirm integer null,
  month_confirm character varying(20) null,
  date_baptism integer null,
  name character varying(255) null,
  age character varying(50) null,
  location character varying(255) null,
  location_baptism character varying(255) null,
  mother_name character varying(255) null,
  father_name character varying(255) null,
  godparents character varying(255) null,
  stipend character varying(100) null,
  minister character varying(255) null,
  created_at timestamp with time zone null default now(),
  parish_id uuid null,
  constraint confirmation_records_pkey primary key (id)
);

alter table public.confirmation_records add column if not exists year_confirm integer;
alter table public.confirmation_records add column if not exists month_confirm character varying(20);
alter table public.confirmation_records add column if not exists date_baptism integer;
alter table public.confirmation_records add column if not exists name character varying(255);
alter table public.confirmation_records add column if not exists age character varying(50);
alter table public.confirmation_records add column if not exists location character varying(255);
alter table public.confirmation_records add column if not exists location_baptism character varying(255);
alter table public.confirmation_records add column if not exists mother_name character varying(255);
alter table public.confirmation_records add column if not exists father_name character varying(255);
alter table public.confirmation_records add column if not exists godparents character varying(255);
alter table public.confirmation_records add column if not exists stipend character varying(100);
alter table public.confirmation_records add column if not exists minister character varying(255);
alter table public.confirmation_records add column if not exists created_at timestamp with time zone default now();
alter table public.confirmation_records add column if not exists parish_id uuid;

create index if not exists confirmation_records_parish_id_idx
  on public.confirmation_records using btree (parish_id);
create index if not exists confirmation_records_name_idx
  on public.confirmation_records using btree (name);

alter table public.confirmation_records enable row level security;

drop policy if exists "Read scoped confirmation records" on public.confirmation_records;
drop policy if exists "Create scoped confirmation records" on public.confirmation_records;
drop policy if exists "Update scoped confirmation records" on public.confirmation_records;
drop policy if exists "Delete scoped confirmation records" on public.confirmation_records;

create policy "Read scoped confirmation records"
on public.confirmation_records for select to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Create scoped confirmation records"
on public.confirmation_records for insert to authenticated
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Update scoped confirmation records"
on public.confirmation_records for update to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
)
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Delete scoped confirmation records"
on public.confirmation_records for delete to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

grant select, insert, update, delete on public.confirmation_records to authenticated;
grant usage, select on sequence public.confirmation_records_id_seq to authenticated;
