-- Run sql/baptism_records.sql first; it defines current_staff_parish_id().

create table if not exists public.marriage_records (
  id bigint generated by default as identity not null,
  entry_no integer null,
  marriage_date date null,
  party_role text null,
  name_family_name text null,
  status text null,
  age integer null,
  origin_of_birth text null,
  residence text null,
  parents text null,
  witness_1 text null,
  witness_2 text null,
  witness_residence text null,
  minister text null,
  remarks text null,
  created_at timestamp with time zone null default now(),
  parish_id uuid null,
  constraint marriage_records_pkey primary key (id)
);

alter table public.marriage_records add column if not exists entry_no integer;
alter table public.marriage_records add column if not exists marriage_date date;
alter table public.marriage_records add column if not exists party_role text;
alter table public.marriage_records add column if not exists name_family_name text;
alter table public.marriage_records add column if not exists status text;
alter table public.marriage_records add column if not exists age integer;
alter table public.marriage_records add column if not exists origin_of_birth text;
alter table public.marriage_records add column if not exists residence text;
alter table public.marriage_records add column if not exists parents text;
alter table public.marriage_records add column if not exists witness_1 text;
alter table public.marriage_records add column if not exists witness_2 text;
alter table public.marriage_records add column if not exists witness_residence text;
alter table public.marriage_records add column if not exists minister text;
alter table public.marriage_records add column if not exists remarks text;
alter table public.marriage_records add column if not exists created_at timestamp with time zone default now();
alter table public.marriage_records add column if not exists parish_id uuid;

create index if not exists marriage_records_parish_id_idx
  on public.marriage_records using btree (parish_id);
create index if not exists marriage_records_name_family_name_idx
  on public.marriage_records using btree (name_family_name);

alter table public.marriage_records enable row level security;

drop policy if exists "Read scoped marriage records" on public.marriage_records;
drop policy if exists "Create scoped marriage records" on public.marriage_records;
drop policy if exists "Update scoped marriage records" on public.marriage_records;
drop policy if exists "Delete scoped marriage records" on public.marriage_records;

create policy "Read scoped marriage records"
on public.marriage_records for select to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Create scoped marriage records"
on public.marriage_records for insert to authenticated
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Update scoped marriage records"
on public.marriage_records for update to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
)
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

create policy "Delete scoped marriage records"
on public.marriage_records for delete to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'diocese'
  or (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') = 'parish'
    and parish_id = public.current_staff_parish_id()
  )
);

grant select, insert, update, delete on public.marriage_records to authenticated;
grant usage, select on sequence public.marriage_records_id_seq to authenticated;
